{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cronjob.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cronjob.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
