{{- if .Values.serviceAccount.create }}
# Optional: create a service account for this release (most deployments use the shared one)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cronjob.serviceAccountName" . }}
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::751442549699:role/standard-service-account
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
