# Config: choose any style, including the new "cylinder_world"
defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.cylinder_world.CylinderWorld
      width: ${sampling:75,120,60}
      height: ${sampling:75,120,60}
      border_width: 1
      agents: 1
      objects:
        generator: ${sampling:10,50,25}

  objects:
    altar:
      cooldown: 255
    generator:
      cooldown: 255
      initial_items: 0
