_target_: metta.mettagrid.curriculum.bucketed.BucketedCurriculum

env_cfg_template_path: /env/mettagrid/object_use/training/easy_all_objects

buckets:
  game.map_builder.room.width:
    range: [15, 50]
    bins: 2
  game.map_builder.room.height:
    range: [15, 50]
    bins: 2
  game.map_builder.room.objects.altar:
    range: [1, 3]
  game.map_builder.room.objects.generator_red:
    range: [1, 3]
  game.map_builder.room.objects.mine_red:
    range: [1, 3]
  game.map_builder.room.objects.wall:
    range: [1, 3]
  game.map_builder.room.objects.block:
    range: [1, 3]
  game.map_builder.room.objects.lasery:
    range: [1, 3]
  game.map_builder.room.objects.lab:
    range: [1, 3]
  game.map_builder.room.objects.factory:
    range: [1, 3]
  game.map_builder.room.objects.temple:
    range: [1, 3]
  objects.altar.initial_items: [0, 1]
  objects.altar.cooldown:
    range: [10, 60]
  objects.generator_red.initial_items: [0, 1]
  objects.generator_red.cooldown:
    range: [10, 60]
  objects.mine_red.cooldown:
    range: [10, 60]
