# @package __global__

# Multiprocessing vectorization configuration for CPU training
#
# This setup uses 4 cores on a Mac to achieve higher SPS (Steps Per Second)
# compared to single-worker mac_serial configuration.
#
# The multiprocessing approach parallelizes environment simulation across workers,
# which is different from GPU parallelization.

device: cpu

vectorization: multiprocessing

trainer:
  num_workers: 4 # Number of "parallel" worker processes (i.e. cores)
  update_epochs: 1
  batch_size: 4096
  minibatch_size: 1024
  forward_pass_minibatch_target_size: 512
  async_factor: 1
  checkpoint_interval: 10
  bptt_horizon: 8
  num_steps: 32
