_target_: mettagrid.map.mapgen.MapGen

width: ${sampling:20,80,40}
height: ${sampling:20,80,40}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 2
  columns: 2

  children:
    - scene:
        _target_: mettagrid.map.scenes.maze.MazeKruskal

        children:
          - where:
              tags:
                - top-left
            scene:
              _target_: mettagrid.map.scenes.inline_ascii.InlineAscii
              data: A
          - where:
              tags:
                - bottom-right
            scene:
              _target_: mettagrid.map.scenes.inline_ascii.InlineAscii
              data: a
