_target_: metta.rl.trainer.MettaTrainer

defaults:
  - puffer
  - _self_

learning_rate: 0.0005570885525880004
gamma: 0.9738787277083967
gae_lambda: 0.857851827593042
update_epochs: 2
vf_coef: 0.7460012193454508
ent_coef: 0.0010326257650369725
batch_size: 524288
minibatch_size: 4096
bptt_horizon: 16
