_target_: mettagrid.map.mapgen.MapGen

width: ${uniform:20,200,50}
height: ${uniform:20,200,50}

border_width: 6

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid

  rows: 2
  columns: 2

  border_width: 0

  children:
  - scene:
      _target_: mettagrid.map.scenes.random.Random

      agents:
        prey: 4
        predator: 1

      objects:
        altar: ${uniform:1,5,1}
        converter: ${uniform:1,15,5}
        generator: ${uniform:1,50,15}
        wall: ${uniform:10,100,40}
