# see reference_design.yaml for explanation of components
_target_: agent.metta_agent.MettaAgent

policy_selector:
  uri: null
  type: top
  range: 0
  metric: final.score
  generation: null
  
observations:
  obs_key: grid_obs
  track_last_action: ${env.track_last_action}
  
clip_range: 3.0
effective_rank_interval: 10
l2_init_weight_update_interval: 0

components:
#necessary source layers: _obs_, _core_
#necessary output layers: _action_param_, _value_
  _obs_: 
    _target_: agent.lib.obs_shaper.ObsShaper
    input_source: null

  obs_normalizer:
    _target_: agent.lib.observation_normalizer.ObservationNormalizer
    input_source: _obs_

  cnn1:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: obs_normalizer
    output_size: 64
    nn_params:
      kernel_size: 5
      stride: 3

  cnn2:
    _target_: agent.lib.nn_layer_library.Conv2d
    input_source: cnn1
    output_size: 64
    nn_params:
      kernel_size: 3
      stride: 1

  obs_flattener:
    _target_: agent.lib.nn_layer_library.Flatten
    input_source: cnn2

  fc1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: obs_flattener
    output_size: 128

  encoded_obs:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: fc1
    output_size: 128

  _core_:
    _target_: agent.lib.lstm.LSTM
    input_source: encoded_obs
    output_size: 128
    nn_params:
      num_layers: 2

  LSTM_encoded_obs_merger:
    _target_: agent.lib.merge_layer.ConcatMergeLayer
    sources:
      - source_name: _core_
      - source_name: _encoded_obs_
      
  critic_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: LSTM_encoded_obs_merger
    output_size: 1024
    nonlinearity: nn.Tanh

  _value_:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: critic_1
    output_size: 1
    nonlinearity: null

  actor_1:
    _target_: agent.lib.nn_layer_library.Linear
    input_source: LSTM_encoded_obs_merger
    output_size: 512

  _action_type_:
    _target_: agent.lib.action.ActionType
    input_source: actor_1
    nonlinearity: null

  _action_param_:
    _target_: agent.lib.action.ActionParam
    input_source: actor_1
    nonlinearity: null