defaults:
  - /env/mettagrid/operant_conditioning_evals/defaults@
  - _self_

game:
  max_steps: 140
  map_builder:
    border_width: 10
    uri: "configs/env/mettagrid/maps/operant_conditioning_evals/shoot_out_hard.map"

