{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "match-scheduler.fullname" . }}-worker-manager
  labels:
    {{- include "match-scheduler.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{- end }}
