{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "match-scheduler.fullname" . }}-worker-manager
  labels:
    {{- include "match-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "match-scheduler.fullname" . }}-worker-manager
subjects:
- kind: ServiceAccount
  name: {{ include "match-scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
