_target_: rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

policy_uri: ???

analysis:

  metric_patterns: null

  metrics:
    - metric: "heart.get"


  queries: null

  baseline_policies: null #if left null will average over policies in stats DB