_target_: metta.rl.eval.eval_stats_analyzer.EvalStatsAnalyzer

policy_uri: ???

view_type: all
output_path: /tmp/dashboard.html
metric: episode_reward

analysis:

  metric_patterns: null

  metrics:
    - metric: episode_reward

  queries: null

  baseline_policies: null

  log_all: true
