defaults:
  - /env/mettagrid/navigation/evals/defaults@
  - _self_

game:
  max_steps: 300

  map_builder:
    _target_: metta.map.mapgen.MapGen
    width: 60
    height: 60
    border_width: 3

    root:
      type: metta.map.scenes.mean_distance.MeanDistance
      params:
        mean_distance: ${sampling:20,30,30}
        objects:
          altar: 3
