defaults:
  - /env/mettagrid-base/mettagrid@

game:
  num_agents: 12  #how many agents are in the map x2
  max_steps: 32
  agent:
    rewards:
      heart: 0.333
  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 6
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/navigation/memory_no_memory.map"

  objects:
    altar:
      cooldown: 255
