defaults:
  - /env/mettagrid/navigation_sequence/defaults@
  - _self_

game:
  max_steps: 400
  map_builder:
    border_width: 5
    uri: "configs/env/mettagrid/maps/navigation_sequence/cylinder_easy.map"
