_target_: metta.mettagrid.curriculum.bucketed.BucketedCurriculum

env_cfg_template_path: /env/mettagrid/navigation/training/terrain_from_numpy

buckets:
  game.map_builder.room.dir:
    values:
      [
        "terrain_maps_nohearts",
        "varied_terrain/balanced_large",
        "varied_terrain/balanced_medium",
        "varied_terrain/balanced_small",
        "varied_terrain/sparse_large",
        "varied_terrain/sparse_medium",
        "varied_terrain/sparse_small",
        "varied_terrain/dense_large",
        "varied_terrain/dense_medium",
        "varied_terrain/dense_small",
        "varied_terrain/maze_large",
        "varied_terrain/maze_medium",
        "varied_terrain/maze_small",
        "varied_terrain/cylinder-world_large",
        "varied_terrain/cylinder-world_medium",
        "varied_terrain/cylinder-world_small",
      ]
  game.map_builder.room.objects.altar:
    range: [2, 18]
    bins: 4

env_overrides: