_target_: metta.mettagrid.curriculum.learning_progress.LearningProgressCurriculum

tasks:
  /env/mettagrid/navigation/training/terrain_from_numpy: 1
  /env/mettagrid/navigation/training/cylinder_world: 1
  /env/mettagrid/navigation/training/varied_terrain_sparse: 1
  /env/mettagrid/navigation/training/varied_terrain_balanced: 1
  /env/mettagrid/navigation/training/varied_terrain_maze: 1
  /env/mettagrid/navigation/training/varied_terrain_dense: 1
  /env/mettagrid/curriculum/navigation/subcurricula/sparse: 1
