num_envs: 1024
num_episodes: 1024
max_time_s: 60
policy_agents_pct: 0.5

policy:
  uri: null
  type: top
  range: 1
  metric: epoch
  filters: {}

baselines:
  elo_scores_path: null
  glicko_scores_path: null
  uri: null
  type: top
  range: 5
  metric: epoch
  filters: {}

stat_categories:
  action.use.altar:
    - action.use.altar

  action.use:
    - action.use

  altar:
    - action.use.altar

  all:
    - action.rotate.energy
    - action.attack
    - action.attack.energy
    - action.move.energy
    - action.gift.energy
    - r3.stolen
    - action.rotate
    - action.attack.altar
    - action.use.altar
    - r1.stolen
    - action.attack.agent
    - shield_damage
    - damage.altar
    - status.shield.ticks
    - action.use.energy.altar
    - action.attack.wall
    - destroyed.wall
    - action.shield.energy
    - r2.gained
    - r3.gained
    - action.move
    - action.use.energy
    - r2.stolen
    - status.frozen.ticks
    - shield_upkeep
    - attack.frozen
    - r1.gained
    - action.use
    - damage.wall

  adversarial:
    - action.attack
    - action.attack.energy
    - action.attack.altar
    - action.attack.agent
    - action.attack.wall
    - damage.altar
    - damage.wall
    - shield_damage
    - attack.frozen
    - r1.stolen
    - r2.stolen
    - r3.stolen
    - destroyed.wall

  shield:
    - shield_damage
    - status.shield.ticks
    - action.shield.energy
    - shield_upkeep
