_target_: rl.pufferlib.eval.EvalSuite

defaults:
  - eval

env: null

evals:
  cylinder:
    env: env/mettagrid/cognitive_evals/cylinder
    policy_agents_pct: 1.0
  radial_maze:
    env: env/mettagrid/cognitive_evals/radial_maze
    policy_agents_pct: 1.0
  navigating_obstacles:
    env: env/mettagrid/cognitive_evals/navigating_obstacles
    policy_agents_pct: 1.0
  short_term_memory:
    env: env/mettagrid/cognitive_evals/short_term_memory
    policy_agents_pct: 1.0
