defaults:
  - mettagrid

game:
  num_agents: 4
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.multi_room.RoomList
    rooms:
      - _target_: mettagrid.config.room.cognitive_evals.radial_maze.RadialMaze
        width: ${uniform:18,22,21}
        height: ${uniform:18,22,21}
        radial_params:
          num_arms: ${uniform:4,8,6}
          arm_length: ${uniform:7,10,7}
          center_radius: ${uniform:2,4,3}              # Set the corridor width to 4 blocks.
      - _target_: mettagrid.config.room.cognitive_evals.radial_maze.RadialMaze
        width: ${uniform:18,22,21}
        height: ${uniform:18,22,21}
        radial_params:
          num_arms: ${uniform:4,8,6}
          arm_length: ${uniform:7,10,7}
          center_radius: ${uniform:2,4,3}                    # Set the corridor width to 4 blocks.
      - _target_: mettagrid.config.room.cognitive_evals.radial_maze.RadialMaze
        width: ${uniform:18,22,21}
        height: ${uniform:18,22,21}
        radial_params:
          num_arms: ${uniform:4,8,6}
          arm_length: ${uniform:7,10,7}
          center_radius: ${uniform:2,4,3}                    # Set the corridor width to 4 blocks.
      - _target_: mettagrid.config.room.cognitive_evals.radial_maze.RadialMaze
        width: ${uniform:18,22,21}
        height: ${uniform:18,22,21}
        radial_params:
          num_arms: ${uniform:4,8,6}
          arm_length: ${uniform:7,10,7}
          center_radius: ${uniform:2,4,3}                       # Set the corridor width to 4 blocks.

  objects:
    altar:
      hp: 30
      cooldown: 1

    mine:
      hp: 30
      cooldown: 1

    generator:
      hp: 30
      cooldown: 1

    armory:
      hp: 30
      cooldown: 1

    lasery:
      hp: 30
      cooldown: 1

    lab:
      hp: 30
      cooldown: 1

    factory:
      hp: 30
      cooldown: 1

    temple:
      hp: 30
      cooldown: 1

    wall:
      hp: ${uniform:1, 20, 10}