_target_: metta.mettagrid.curriculum.random.RandomCurriculum

tasks:
  /env/mettagrid/curriculum/arena/learning_progress: 5
  /env/mettagrid/curriculum/navigation/learning_progress: 3
  /env/mettagrid/curriculum/object_use: 2

env_overrides:
  game:
    num_agents: 24
