_target_: metta.mettagrid.curriculum.prioritize_regressed.PrioritizeRegressedCurriculum

tasks:
  /env/mettagrid/navigation_sequence/experiments/mem_balanced: 1
  /env/mettagrid/navigation_sequence/experiments/mem_sparse: 1
  /env/mettagrid/navigation_sequence/experiments/mem_maze: 1
  /env/mettagrid/navigation_sequence/experiments/mem_dense: 1
