_target_: metta.mettagrid.curriculum.random.RandomCurriculum

#use this environment pretrained on a policy that is the best at navigation sequence already
#gd_backchain_mem_pretained:v18
tasks:
  /env/mettagrid/curriculum/navigation/learning_progress: 5
  /env/mettagrid/curriculum/navsequence/mem_medium: 5
  # /env/mettagrid/curriculum/navsequence/mem_hard: 2
