_target_: metta.mettagrid.curriculum.random.RandomCurriculum

#train this pretrained on our best navigation policy
#dd_navigation_curriculum:v54
tasks:
  /env/mettagrid/curriculum/navigation/learning_progress: 1
  /env/mettagrid/curriculum/navsequence/backchain_seq: 1
  /env/mettagrid/curriculum/navsequence/mem_medium: 1
