_target_: metta.mettagrid.curriculum.prioritize_regressed.PrioritizeRegressedCurriculum

tasks:
  /env/mettagrid/navigation_sequence/experiments/mem_balanced: 1
  /env/mettagrid/navigation_sequence/experiments/mem_sparse: 1
  /env/mettagrid/navigation_sequence/experiments/mem_maze: 1
  /env/mettagrid/navigation_sequence/experiments/mem_dense: 1
  /env/mettagrid/navigation_sequence/experiments/terrain_from_numpy: 1
  /env/mettagrid/navigation_sequence/experiments/sequence_sparse: 1
  /env/mettagrid/navigation_sequence/experiments/sequence_balanced: 1
  /env/mettagrid/navigation_sequence/experiments/sequence_maze: 1
  /env/mettagrid/navigation_sequence/experiments/sequence_dense: 1
  /env/mettagrid/navigation_sequence/experiments/hard_mem_sparse: 1
  /env/mettagrid/navigation_sequence/experiments/hard_mem_balanced: 1
  /env/mettagrid/navigation_sequence/experiments/hard_mem_maze: 1
  /env/mettagrid/navigation_sequence/experiments/hard_mem_dense: 1
