defaults:
  - /env/mettagrid/object_use/evals/defaults@
  - /env/mettagrid/game/objects/combat@game.objects
  - _self_

game:
  max_steps: 80
  agent:
    rewards:
      armor: 1
  map_builder:
    root:
      params:
        objects:
          armory: 1
  objects:
    armory:
      cooldown: 255
      initial_resource_count: 0
