
defaults:
  - ../../mettagrid@

game:
  num_agents: 20
  max_steps: 100

  agent:
    rewards:
      armor: 3
      ore.red: 0

  objects:
    mine.red:
      initial_items: 3
      output_ore: 3
      cooldown: 255
    armory:
      initial_items: 0
      cooldown: 255

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    border_width: 3

    room:
      _target_: mettagrid.config.room.random.Random
      width: 15
      height: 15
      border_width: 3

      agents: 1

      objects:
        armory: 1
        mine: 1
