defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_
  
game:
  num_agents: 20  #how many agents are in the map x2
  max_steps: 400

  objects:
    altar:
      cooldown: 255
    wall:
      hp: 1
    lasery:
      initial_items: 20

  agent:
    rewards:
      heart: 3

  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/object_use/shoot_out.map"
