_target_: metta.map.mapgen.MapGen

width: 200
height: 100

root:
  type: metta.map.scenes.room_grid.RoomGrid
  params:
    rows: 2
    columns: 4

  children:
    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/blocks.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/dungeons.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/simple.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/blob.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/blob2.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/blob3.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/mazelike1.yaml

    - limit: 1
      lock: lock1
      order_by: first
      scene: /wfc/mazelike2.yaml
