_target_: metta.mettagrid.room.multi_room.RoomList
rooms:
  - _target_: metta.mettagrid.room.maze.MazeKruskal
    width: ${sampling:10,40,20}
    height: ${sampling:10,40,20}
    start_pos: [1, 0]
    end_pos:
      - ${sub:${..width},2}
      - ${sub:${..height},2}
    branching: ${sampling:0.1,0.95,0.7}
  - _target_: metta.mettagrid.room.maze.MazeKruskal
    width: ${sampling:10,40,20}
    height: ${sampling:10,40,20}
    start_pos: [1, 0]
    end_pos:
      - ${sub:${..width},2}
      - ${sub:${..height},2}
    branching: ${sampling:0.1,0.95,0.7}
  - _target_: metta.mettagrid.room.maze.MazeKruskal
    width: ${sampling:10,40,20}
    height: ${sampling:10,40,20}
    start_pos: [1, 0]
    end_pos:
      - ${sub:${..width},2}
      - ${sub:${..height},2}
    branching: ${sampling:0.1,0.95,0.7}
  - _target_: metta.mettagrid.room.maze.MazeKruskal
    width: ${sampling:10,40,20}
    height: ${sampling:10,40,20}
    start_pos: [1, 0]
    end_pos:
      - ${sub:${..width},2}
      - ${sub:${..height},2}
    branching: ${sampling:0.1,0.95,0.7}
