_target_: metta.mettagrid.curriculum.bucketed.BucketedCurriculum

env_cfg_template: /env/mettagrid/extended_sequence/backchain1

buckets:
  game.map_builder.room.dir:
    values:
      [
        "varied_terrain/sparse_small",
        "varied_terrain/balanced_small",
        "varied_terrain/dense_small",
      ]
