image:
  registry: ""
  name: metta-policy-evaluator-local
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  BACKEND_URL: "http://host.docker.internal:8000"

datadog:
  enabled: true
  datadog:
    clusterName: "kind-metta-local"
    tags:
      - "env:local"
  agents:
    containers:
      agent:
        env:
          - name: DD_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
