orchestrator:
  enabled: false

image:
  registry: ""
  name: metta-policy-evaluator-local
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  BACKEND_URL: "http://host.docker.internal:8000"

datadog:
  enabled: false

evalScheduler:
  enabled: false

watcher:
  enabled: true
