# This is a modified `sample.yaml` config with sampling removed, for benchmark_env_perf.py script.
report_stats_interval: 100

game:
  num_agents: 24
  num_observation_tokens: 100

  inventory_item_names:
    - ore_red
    - ore_blue
    - ore_green
    - battery_red
    - battery_blue
    - battery_green
    - heart
    - armor
    - laser
    - blueprint

  map_builder:
    _target_: metta.mettagrid.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: metta.mettagrid.room.random.Random
      width: 25
      height: 25
      border_width: 0
      seed: 42

      agents: 6

      objects:
        mine_red: 10
        generator_red: 2
        altar: 1
        armory: 1
        lasery: 1
        lab: 1
        factory: 1
        temple: 1

        block: 20
        wall: 20

  obs_width: 11
  obs_height: 11
  max_steps: 1000

  agent:
    default_resource_limit: 50
    freeze_duration: 10

    rewards:
      inventory:
        ore_red: 0.005
        ore_blue: 0.005
        ore_green: 0.005
        battery_red: 0.01
        battery_blue: 0.01
        battery_green: 0.01
        battery_red_max: 5
        battery_blue_max: 5
        battery_green_max: 5
        heart: 1

  groups:
    agent:
      id: 0
      sprite: 0
      props: {}

    team_1:
      id: 1
      sprite: 1
      group_reward_pct: 0.5
      props: {}

    team_2:
      id: 2
      sprite: 4
      group_reward_pct: 0.5
      props: {}

    team_3:
      id: 3
      sprite: 8
      group_reward_pct: 0.5
      props: {}

    team_4:
      id: 4
      sprite: 1
      group_reward_pct: 0.5
      props: {}

    prey:
      id: 5
      sprite: 12
      props: {}

    predator:
      id: 6
      sprite: 6
      props: {}

  objects:
    altar:
      type_id: 8
      input_resources:
        battery_red: 3
      output_resources:
        heart: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 1

    mine_red:
      type_id: 2
      output_resources:
        ore_red: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 1

    mine_blue:
      type_id: 3
      color: 1
      output_resources:
        ore_blue: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 1

    mine_green:
      type_id: 4
      output_resources:
        ore_green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 50
      initial_resource_count: 1

    generator_red:
      type_id: 5
      input_resources:
        ore_red: 1
      output_resources:
        battery_red: 1
      color: 0
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 1

    generator_blue:
      type_id: 6
      input_resources:
        ore_blue: 1
      output_resources:
        battery_blue: 1
      color: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 1

    generator_green:
      type_id: 7
      input_resources:
        ore_green: 1
      output_resources:
        battery_green: 1
      color: 2
      max_output: 5
      conversion_ticks: 1
      cooldown: 25
      initial_resource_count: 1

    armory:
      type_id: 9
      input_resources:
        ore_red: 3
      output_resources:
        armor: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 1

    lasery:
      type_id: 10
      input_resources:
        ore_red: 1
        battery_red: 2
      output_resources:
        laser: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 1

    lab:
      type_id: 11
      input_resources:
        ore_red: 3
        battery_red: 3
      output_resources:
        blueprint: 1
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 1

    factory:
      type_id: 12
      input_resources:
        blueprint: 1
        ore_red: 5
        battery_red: 5
      output_resources:
        armor: 5
        laser: 5
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 1

    temple:
      type_id: 13
      input_resources:
        heart: 1
        blueprint: 1
      output_resources:
        heart: 5
      max_output: 5
      conversion_ticks: 1
      cooldown: 5
      initial_resource_count: 1

    wall:
      type_id: 1
      swappable: false

    block:
      type_id: 14
      swappable: true

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: true
    get_items:
      enabled: true
    attack:
      enabled: true
      consumed_resources:
        laser: 1
      defense_resources:
        armor: 1
    swap:
      enabled: true
    change_color:
      enabled: true
    change_glyph:
      enabled: true
      number_of_glyphs: 4
