apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: skypilot-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 15m
    consolidationPolicy: WhenEmpty
  replicas: 2
  template:
    metadata:
      labels:
        workload-type: skypilot
        skypilot.co/accelerator: l4
    spec:
      expireAfter: 2h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - g5.2xlarge   # 8 vCPUs, 1 A10G GPU
        - g6.2xlarge   # 8 vCPUs, 1 L4 GPU
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      terminationGracePeriod: 1h0m0s
      taints:
      - key: workload-type
        value: skypilot
        effect: NoSchedule
