host: observatory.softmax-research.net

image:
  registry: 751442549699.dkr.ecr.us-east-1.amazonaws.com
  name: metta-app-frontend
  tag: "" # will be set by CI/CD pipeline

cert_manager_issuer: letsencrypt

replicaCount: 2
