defaults:
  - mettagrid
  - override game/groups: teams
  - override game/objects:
      - basic
      - mines
  - _self_

group_reward_pct: 0

game:
  num_agents: 36
  map_builder:
    _target_: metta.map.mapgen.MapGen

    width: 50
    height: 50

    border_width: 6

    root:
      type: metta.map.scenes.room_grid.RoomGrid

      params:
        rows: 4
        columns: 4
        border_width: 0

      children:
        - limit: 1
          scene:
            type: metta.map.scenes.random.Random
            params:
              objects:
                mine_red: 5
        - limit: 1
          scene:
            type: metta.map.scenes.random.Random
            params:
              too_many_is_ok: false
              objects:
                altar: 4
                mine_red: 1
              agents:
                team_1: 36

  agent:
    rewards:
      inventory:
        heart: 1
        ore_red: 0.005

  objects:
    altar:
      input_resources:
        battery_red: 0
        ore_red: 2
      output_resources:
        heart: 1
      max_output: 50
      conversion_ticks: 1
      cooldown: 10
      initial_resource_count: 1

    mine_red:
      output_resources:
        ore_red: 1
      color: 0
      max_output: 10
      conversion_ticks: 1
      cooldown: 100
      initial_resource_count: 10

  groups:
    team_1:
      group_reward_pct: ${....group_reward_pct}
