defaults:
  - mettagrid

game:
  num_agents: 6
  max_steps: 250

  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 5
    room:
      _target_: mettagrid.config.room.ascii_room.AsciiRoom
      border_width: 1
      uri: "configs/env/mettagrid/maps/triangle.map"
      

  objects:
    altar:
      cooldown: 250
      use_cost: 250
    agent:
      initial_energy: 250
      max_energy: 250
      upkeep.time: 0

  actions:
    move:
      cost: 0
    attack:
      cost: 255
      # enabled: false
    shield:
      cost: 255
      # enabled: false
