defaults:
  - mettagrid

sampling: 1
game:
  num_agents: 3
  max_steps: 250

  map_builder:

    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    room:
      _target_: mettagrid.config.room.cylinder.Cylinder
      border_width: 1
      width: ${uniform:10,40,21}
      height: ${uniform:10,40,21}
      cylinder_params:
        length: ${uniform:3,5,10}
        horizontal: true | false
        both_ends: true | false
