defaults:
  - mettagrid

game:
  num_agents: 6
  max_steps: 250

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    room:
      _target_: mettagrid.config.room.maze.Maze
      width: ${uniform:10,40,21}
      height: ${uniform:10,40,21}
      start_pos: [1, 1]
      end_pos:
        - ${sub:${..width},2}
        - ${sub:${..height},2}
      branching: ${uniform:0.1,0.95,0.7}

  objects:
    altar:
      cooldown: 250
      use_cost: 250
    agent:
      initial_energy: 250
      max_energy: 250
      upkeep.time: 0

  actions:
    move:
      cost: 0
    attack:
      cost: 255
      # enabled: false
    shield:
      cost: 255
      # enabled: false
