defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 11
  max_steps: 100

  groups:
    mazer:
      id: 0
      sprite: 10
      props: {}

  map_builder:
    _target_: metta.mettagrid.room.room_list.RoomList
    border_width: 2

    rooms:
      # single agent small room
      - _target_: metta.mettagrid.room.random.Random
        border_width: 2
        width: ${sampling:5,20,10}
        height: ${sampling:5,20,10}
        agents: 1
        objects:
          altar: 1
          generator_red: 3
          wall: ${..width}

      # multi agent small room
      - _target_: metta.mettagrid.room.random.Random
        border_width: 2
        width: ${sampling:5,20,10}
        height: ${sampling:5,20,10}
        agents: 3
        objects:
          altar: 1
          generator_red: 3
          wall: ${..width}

      # 2 agent scarce room
      - _target_: metta.mettagrid.room.random.Random
        border_width: 2
        width: ${sampling:5,20,10}
        height: ${sampling:5,20,10}
        agents: 2
        objects:
          altar: 1
          generator_red: 1
          wall: ${..width}

      # predator and prey room
      - _target_: metta.mettagrid.room.random.Random
        border_width: 2
        width: ${sampling:5,20,10}
        height: ${sampling:5,20,10}
        agents:
          predator: 1
          prey: 3
        objects:
          altar: 1
          generator_red: 1
          wall: ${..width}

      # maze
      # - _target_: metta.mettagrid.room.maze.Maze
      #   border_width: 2
      #   width: ${make_odd:${sampling:10,40,21}}
      #   height: ${make_odd:${sampling:10,40,21}}
      #   start_pos: [1, 1]
      #   end_pos:
      #   - ${sub:${..width},2}
      #   - ${sub:${..height},2}
      #   branching: ${sampling:0.1,0.95,0.7}

      # break room
      - _target_: metta.mettagrid.room.room_list.RoomList
        border_width: 2
        rooms:
          - _target_: metta.mettagrid.room.random.Random
            border_width: 0
            width: ${sampling:5,20,10}
            height: ${sampling:5,20,10}
            agents: 1
            objects:
              generator_red: 1
              wall: ${..width}
          - _target_: metta.mettagrid.room.random.Random
            border_width: 1
            width: ${sampling:5,20,10}
            height: ${sampling:5,20,10}
            objects:
              altar: 1
              wall: ${..width}
