defaults:
  - /env/mettagrid/simple@
  - _self_

game:
  group_reward_pct: 0.5

  map_builder:
    border_width: 6
    room:
      border_width: 2
      agents:
        team_1: 3
        team_2: 3

  groups:
    team_1:
      group_reward_pct: ${...group_reward_pct}

    team_2:
      group_reward_pct: ${...group_reward_pct}
