_target_: mettagrid.map.mapgen.MapGen

width: 80
height: 60

# Rooms are made with BSP, but tunnels are dug with MakeConnected.
# The result looks worse, but it serves as a nice test for the MakeConnected scene.

root:
  _target_: mettagrid.map.scenes.bsp.BSP
  rooms: 10
  min_room_size: 3
  min_room_size_ratio: 0.5
  max_room_size_ratio: 0.9
  skip_corridors: true # disable BSP corridors

  children:
    - where: full
      scene:
        _target_: mettagrid.map.scenes.make_connected.MakeConnected
