_target_: mettagrid.map.mapgen.MapGen

width: 100
height: 80

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid

  rows: 2
  columns: 2

  children:
    - limit: 1
      order_by: first
      lock: lock1
      scene: ./configs/scenes/convchain/blob.yaml

    - limit: 1
      order_by: first
      lock: lock1
      scene: ./configs/scenes/convchain/c_shape.yaml

    - limit: 1
      order_by: first
      lock: lock1
      scene: ./configs/scenes/convchain/diagonal.yaml

    - limit: 1
      order_by: last
      lock: lock1
      scene: ./configs/scenes/convchain/dungeon.yaml

    - where: full
      scene:
        _target_: mettagrid.map.scenes.make_connected.MakeConnected
