_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      layers:
      - sampling_function : mettagrid.map.scenes.simsam_functions.radial_symmetry   # radial symmetry
        saturation: ${choose:1,2,3,4}
        function_parameters:
          x_zoom: ${uniform:0.05,0.2}                       # scaling along x
          y_zoom: ${uniform:0.05,0.2}                       # scaling along y
          angle_theta: ${uniform:0,1}                             # additional rotation in 2*pi radians
          symmetry: ${int:${uniform:2,9}}               # symmetry type
          xc: ${triangular:-0.7,0.0,0.7}                # x off-center
          yc: ${triangular:-0.7,0.0,0.7}                # y off-center
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise   # random noise
        saturation: ${uniform:0.0,0.5}
        function_parameters:
          x_zoom: ${uniform:0.01,0.5}                       # scaling along x
          y_zoom: ${uniform:0.01,0.5}                       # scaling along y

      cutoff: ${uniform:0.02,0.63}                         # global cutoff threshold less number -> less walls
      force_seed: 0 # 0 will use random seeds, any other integer will force the seed. Requires all above parameters to be fixed to produce identical results
