_target_: mettagrid.map.scenes.convchain.ConvChain
pattern_size: 4
iterations: 10
temperature: 0.2
pattern: |
  |            |
  |  # #   #   |
  | # # # # #  |
  |            |
  |#   #     # |
  | # #     #  |
  |  #     #   |
  | # #   #    |
  |#   # #     |
  |            |
