defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 2  #how many agents are in the map x2
  max_steps: 100
  agent:
    rewards:
      heart: 1
  map_builder:

    _target_: mettagrid.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/cooperation/cooperate-or-defect_test.map"

  objects:
    altar:
      cooldown: 100
      input_battery: 1
      output_heart: 1
      max_output: 100
      initial_items: 0
    generator:
      cooldown: 100
      input_ore: 1
      output_battery: 1
      max_output: 100
      initial_items: 0
    mine:
      cooldown: 100
      max_output: 100
      initial_items: 1