defaults:
  - common
  - agent: simple
  - trainer: puffer
  - eval: eval_suite
  - analyzer: eval_analyzer
  - wandb

cmd: eval
eval_db_uri: wandb://artifacts/navigation_evaldb_only_hearts
run: ???
data_dir: ./train_dir
run_dir: ${data_dir}/${run}

torch_deterministic: true
vectorization: multiprocessing
