run: ???
data_dir: ./train_dir
run_dir: ${data_dir}/${run}
sweep_id: null

vectorization: multiprocessing
dashboard: false

seed: 1
device: cpu
torch_deterministic: true
eval_db_uri: wandb://artifacts/eval_stats

defaults:
  - agent: simple
  - env/mettagrid@env: simple
  - trainer: puffer
  - sweep: sweep
  - hardware: macbook
  - eval: example_suite
  - analyzer: analyzer

wandb:
  enabled: False
  track: False
  project: metta
  entity: metta-research
  group: metta
  name: ${run}
