defaults:
  - common
  - agent: simple
  - trainer: puffer
  - eval: all
  - analyzer: eval_analyzer
  - wandb: metta_research
  - _self_
  
cmd: eval
eval_db_uri: null
run: ???
data_dir: ./train_dir
run_dir: ${data_dir}/${run}

torch_deterministic: true
vectorization: multiprocessing
