defaults:
  - /env/mettagrid/mettagrid@
  - _self_

sampling: 1

game:
  num_agents: 4
  agent:
    ore.red_max: ${sampling:1,5,3}
    battery.red_max: ${sampling:1,5,3}
    rewards:
      action_failure_penalty: 0
      ore.red: ${sampling:0.005,0.1, 0.01}
      battery.red: ${sampling:0.01,0.3, 0.1}
      heart: 1
      heart_max: 1000
  map_builder:
    _target_: metta.mettagrid.room.multi_room.MultiRoom
    num_rooms: ${..num_agents}
    border_width: 6
    room:
      _target_: metta.mettagrid.room.terrain_from_numpy.TerrainFromNumpy
      border_width: ${sampling:1,6,3}
      agents: 1
      objects:
        mine.red: ${sampling:3,15,2}
        generator.red: ${sampling:3,15,2}
        altar: ${sampling:1,15,2}
  objects:
    altar:
      input_battery.red: 1
      initial_items: ${choose:0,0,0,1}
      cooldown: ${sampling:5, 20, 10}
    generator.red:
      initial_items: ${choose:0,0,0,1}
      cooldown: ${sampling:5, 20, 10}
    mine.red:
      cooldown: ${sampling:15, 50, 10}
