defaults:
  - sim_suite
  - _self_

name: navsequence

simulations:
  navigation_sequence/cylinder:
    env: env/mettagrid/navigation_sequence/evals/cylinder
  navigation_sequence/obstacles0:
    env: env/mettagrid/navigation_sequence/evals/obstacles0
  navigation_sequence/obstacles1:
    env: env/mettagrid/navigation_sequence/evals/obstacles1
  navigation_sequence/obstacles2:
    env: env/mettagrid/navigation_sequence/evals/obstacles2
  navigation_sequence/obstacles3:
    env: env/mettagrid/navigation_sequence/evals/obstacles3
  navigation_sequence/corridors:
    env: env/mettagrid/navigation_sequence/evals/corridors
  navigation_sequence/cylinder_easy:
    env: env/mettagrid/navigation_sequence/evals/cylinder_easy
  navigation_sequence/honeypot:
    env: env/mettagrid/navigation_sequence/evals/honeypot
  navigation_sequence/knotty:
    env: env/mettagrid/navigation_sequence/evals/knotty
  navigation_sequence/memory_palace:
    env: env/mettagrid/navigation_sequence/evals/memory_palace
  navigation_sequence/radial_large:
    env: env/mettagrid/navigation_sequence/evals/radial_large
  navigation_sequence/radial_mini:
    env: env/mettagrid/navigation_sequence/evals/radial_mini
  navigation_sequence/radial_small:
    env: env/mettagrid/navigation_sequence/evals/radial_small
  navigation_sequence/swirls:
    env: env/mettagrid/navigation_sequence/evals/swirls
  navigation_sequence/thecube:
    env: env/mettagrid/navigation_sequence/evals/thecube
  navigation_sequence/walkaround:
    env: env/mettagrid/navigation_sequence/evals/walkaround
