defaults:
  - sim_suite
  - _self_

name: object_use

simulations:
  object_use/altar_use_free:
    env: env/mettagrid/object_use/evals/altar_use_free
  object_use/armory_use_free:
    env: env/mettagrid/object_use/evals/armory_use_free
  object_use/armory_use:
    env: env/mettagrid/object_use/evals/armory_use
  object_use/generator_use_free:
    env: env/mettagrid/object_use/evals/generator_use_free
  object_use/generator_use:
    env: env/mettagrid/object_use/evals/generator_use
  object_use/lasery_use_free:
    env: env/mettagrid/object_use/evals/lasery_use_free
  object_use/lasery_use:
    env: env/mettagrid/object_use/evals/lasery_use
  object_use/mine_use:
    env: env/mettagrid/object_use/evals/mine_use
  object_use/shoot_out:
    env: env/mettagrid/object_use/evals/shoot_out
  object_use/swap_in:
    env: env/mettagrid/object_use/evals/swap_in
  object_use/swap_out:
    env: env/mettagrid/object_use/evals/swap_out
  object_use/temple_use_free:
    env: env/mettagrid/object_use/evals/temple_use_free
  object_use/full_sequence:
    env: env/mettagrid/object_use/evals/full_sequence
