defaults:
  - sim_suite
  - _self_

name: sweep_eval

simulations:
  navigation/emptyspace_withinsight:
    env: env/mettagrid/navigation/evals/emptyspace_withinsight
  simple:
    env: env/mettagrid/simple
# selector_type: "latest"
