_target_: metta.mettagrid.curriculum.random.RandomCurriculum

tasks:
  /env/mettagrid/operant_conditioning/single_conversion/3_converters/generator_red: 1
  /env/mettagrid/operant_conditioning/single_conversion/3_converters/generator_blue: 1
  /env/mettagrid/operant_conditioning/single_conversion/3_converters/generator_green: 1
