defaults:
  - /env/mettagrid/multiagent/evals/defaults@
  - _self_

game:
  num_agents: 2 #how many agents are in the map x2
  max_steps: 75
  agent:
    rewards:
      heart: 1.0
  map_builder:
    uri: "configs/env/mettagrid/maps/multiagent/choose_an_altar_team.map"

  objects:
    altar:
      input_battery: 9
      output_heart: 1
      initial_items: 0
    generator.red:
      max_output: 3
      initial_items: 3
