defaults:
  - /env/mettagrid/mettagrid@
  - _self_

game:
  num_agents: 2 #how many agents are in the map x2
  max_steps: 38

  agent:
    rewards:
      heart: 0.333

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 1
    room:
      _target_: mettagrid.config.room.ascii.Ascii
      border_width: 1
      uri: "configs/env/mettagrid/maps/multiagent/wallblocker.map"

  objects:
    altar:
      cooldown: 255
