defaults:
- simple

observation_encoder:
  _target_: agent.simple_encoder.IMPALAishCNN
  cnn_channels: [32, 64]
  activation: leaky_relu
  obs_key: grid_obs
  normalize_features: true
  auto_normalize: false
  track_last_action: ${env.track_last_action}
  kinship: ${env.game.kinship}

  fc:
    layers: 1
    output_dim: 128

critic:
  hidden_sizes: [128]

actor:
  hidden_sizes: [128]
