defaults:
  - simple

observation_encoder:
  cnn_channels: 128

fc:
  layers: 3
  output_dim: 128

core:
  rnn_num_layers: 2
  rnn_size: 512

critic:
  hidden_sizes: [1024] #set to [] for no hidden layer

actor:
  hidden_sizes: [512]
