defaults:
  - /env/mettagrid/navigation/training/defaults@
  - _self_

game:
  num_agents: 4
  map_builder:
    room:
      _target_: metta.mettagrid.room.terrain_from_numpy.TerrainFromNumpy
      border_width: 3
      agents: 1
      dir: ${choose:varied_terrain/cylinder-world_large,varied_terrain/cylinder-world_medium,varied_terrain/cylinder-world_small}
      objects:
        altar: 30
  objects:
    altar:
      cooldown: 1000
      input_battery:red: 3
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      initial_items: 1
