
defaults:
  - navigation_defaults

game:
  num_agents: 20

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 20
    border_width: 3

    room:
      _target_: mettagrid.config.room.mean_distance.MeanDistance
      width: 25
      height: 25
      mean_distance: 15
      border_width: 3

      agents: 1

      objects:
        altar: 3
        wall: ${uniform:10,15,12}
