_target_: metta.util.mettagrid_env_set.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.5
  /env/mettagrid/navigation/training/varied_terrain: 0.5
