_target_: mettagrid.mettagrid_env.MettaGridEnvSet

num_agents: 4

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/varied_terrain


probabilities:
  - 0.5
  - 0.5
