_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 4
sampling: 1

game:
  num_agents: ${..num_agents}

envs:
  /env/mettagrid/navigation/training/terrain_from_numpy: 0.5
  /env/mettagrid/navigation/training/varied_terrain: 0.4
  /env/mettagrid/navigation/training/cylinder_world: 0.1
