_target_: metta.env.mettagrid_env_set.MettaGridEnvSet

num_agents: 4
sampling: 1

game:
  num_agents: ${..num_agents}

envs:
  - /env/mettagrid/navigation/training/terrain_from_numpy
  - /env/mettagrid/navigation/training/cylinder_world
  - /env/mettagrid/navigation/training/varied_terrain_sparse
  - /env/mettagrid/navigation/training/varied_terrain_balanced
  - /env/mettagrid/navigation/training/varied_terrain_maze
  - /env/mettagrid/navigation/training/varied_terrain_dense

probabilities:
  - 0.166
  - 0.166
  - 0.166
  - 0.166
  - 0.166
  - 0.166
