_target_: mettagrid.curriculum.curriculum.LowRewardCurriculum

tasks:
  /env/mettagrid/memory/training/easy: 0.5
  /env/mettagrid/memory/training/medium: 0.5
  /env/mettagrid/memory/training/hard: 0.5

env_overrides:
  sampling: 1
  game:
    num_agents: 16
