defaults:
  - /env/mettagrid-base/mettagrid@

game:
  num_agents: 4  #how many agents are in the map x2

  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.terrain_from_numpy.TerrainFromNumpy
      border_width: 1
      dir: "terrain_maps_nohearts"
      num_agents: 1
      generators: true
  objects:
    generators:
      initial_items: 1
    altar:
      cooldown: 100
      input_battery: 1
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      initial_items: 1
