defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

sampling: 1

game:
  max_steps: 1000
  num_agents: 4
  map_builder:
    _target_: mettagrid.config.room.multi_room.MultiRoom
    num_rooms: 4
    border_width: 6

    room:
      _target_: mettagrid.config.room.navigation.varied_terrain.VariedTerrain
      width: 40
      height: 40 
      border_width: ${sampling:1,6,3}
      agents: 1
      style: all-sparse # ${choose:"sparse-altars-dense-objects","all-sparse","all-dense","balanced","dense-altars-sparse-objects"}

  objects:
    altar:
      cooldown: 1000
      input_battery: 3
      output_heart: 1
      max_output: 5
      conversion_ticks: 1
      initial_items: 1