apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.serviceAccount.create }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

