# @package __global__

seed: null

defaults:
  # - override /env/mettagrid@env: simple
  - override /agent: exp_02a
  # - override /sweep: fast
  # - override /eval: eval_suite
  # - override /analyzer: train_analyzer

policy_uri: wandb://run/alex.trainee.002
npc_policy_uri: null
eval_db_uri: null

env:
  game:
    max_steps: 1000

trainer:
  env: env/mettagrid/prog_1b.yaml
  evaluate_interval: 0
  # kickstart:
  #   teacher_uri: wandb://run/b.daphne.multicolor_ore.r.5

eval:
  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  eval_db_uri: ${..eval_db_uri}
  num_envs: 10
  num_episodes: 10
  max_time_s: 60

analyzer:
  analysis:
    metrics:
    - metric: "action.use.altar.agent"

sweep:
  metric: "action.use.altar.agent"

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

run_id: 120
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
