# @package __global__

seed: null

defaults:
  # - override /env/mettagrid@env: simple
  # - override /agent: non_robust_puffer
  - _self_

policy_uri: puffer:///tmp/puffer_metta.pt
npc_policy_uri: null
eval_db_uri: null

env_overrides:
  game:
    max_steps: 1000

env:
  game:
    max_steps: 1000

eval:
  policy_uri: ${..policy_uri}
  npc_policy_uri: ${..npc_policy_uri}
  eval_db_uri: ${..eval_db_uri}
  # env: /env/mettagrid/prog_3.yaml
  # num_envs: 10
  # num_episodes: 10
  # max_time_s: 60

analyzer:
  analysis:
    metrics:
      - metric: "action.use.altar.agent"

sweep:
  metric: "action.use.altar.agent"

wandb:
  enabled: true
  track: true
  checkpoint_interval: 1

run_id: 505
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ${run_dir}/checkpoints
sweep_name: "${oc.env:USER}.local.sweep.${run_id}"
