# @package __global__

defaults:
  # - /sim/all@replay_job.sim
  - _self_

trainer:
  env: env/mettagrid/cooperation/training/overcooked
  # initial_policy:
    uri: wandb://run/mrazo_object-use_allobs_large-small-multienv_v03
  evaluate_interval: 100
  checkpoint_interval: 100

replay_job:
  policy_uri: wandb://run/mrazo_object-use_allobs_large-small-multienv_v03:v01
  # wandb.enabled: false
  wandb.track: false


run: mrazo_overcooked_nav-obj-use_pretrained_v01