name: "Build Library Backend Docker Image"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - 09-08-library_worker_on_eks
    paths:
      - "library/**"
      - "devops/charts/library/**"
      - ".github/workflows/build-library-image.yml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # up from default of 10 minutes
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build-image
        uses: ./.github/actions/docker-build
        with:
          image_name: softmax-library
          dockerfile: library/Dockerfile
          aws_role: ${{ vars.AWS_ROLE }}

      - name: Deploy helm chart
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/09-08-library_worker_on_eks'
        run: |
          aws eks update-kubeconfig --name main --region us-east-1
          helm upgrade -n library library ./devops/charts/library \
            --set image.tag=${{ steps.build-image.outputs.tag }}
