name: "Build (and sometimes Deploy) to GitHub Pages"
on:
  push:
    paths: &site_paths
      - "packages/mettagrid/nim/mettascope/**"
      - ".github/workflows/**"
  pull_request:
    paths: *site_paths
  workflow_dispatch: {}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configure concurrency to always run
concurrency:
  group: pages-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to ensure we don't hit caching issues

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          install-mode: "minimal"

      # setup-environment has it's own cache for installing `nim` however it lacks dependencies for mettascope
      # so we add our own cache step here to cache dependencies for mettascope for performance
      - name: Cache Nim dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: nim-binary-${{ runner.os }}-${{ hashFiles('packages/mettagrid/nim/mettascope/mettascope.nimble') }}
          restore-keys: |
            nim-binary-${{ runner.os }}-

      - name: Install Mettascope
        run: |
          ./mettascope/install.sh

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build mettascope
        run: |
          cd packages/mettagrid/nim/mettascope
          nimble install -y
          nimble deps --tree
          cd ../../../..
          mkdir -p packages/mettagrid/nim/mettascope/dist
          nim c -d:emscripten packages/mettagrid/nim/mettascope/src/mettascope.nim
          ls -la packages/mettagrid/nim/mettascope/dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment directory
        run: |
          mkdir -p deploy/mettascope
          cp -r packages/mettagrid/nim/mettascope/dist/* deploy/mettascope/

      - name: Upload artifact
        # Only upload artifact for main branch
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./deploy"

      - name: Deploy to GitHub Pages
        # Only deploy for main branch
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
