name: "Build Docker Image"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *" # 7 AM UTC (11 PM PST / 12 AM PDT)

jobs:
  build-and-push-image:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 20 # up from default of 10 minutes
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # - name: Read Bazelisk version
      #   id: read-bazelisk-version
      #   run: |
      #     BAZELISK_VERSION=$(cat .bazeliskversion)
      #     echo "bazelisk_version=$BAZELISK_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        uses: ./.github/actions/docker-build
        with:
          image_name: metta
          dockerfile: devops/docker/Dockerfile
          aws_role: ${{ vars.AWS_ROLE }}
          # bazelisk_version: ${{ steps.read-bazelisk-version.outputs.bazelisk_version }}
